server:
  port: ${USER_SERVICE_PORT:80}

spring:
  application:
    name: user-service
  main:
    web-application-type: reactive

  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      retries: 3
      acks: all
    consumer:
      group-id: user-service
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8080/realms/ecommerce}

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ecommerce}
  realm: ${KEYCLOAK_REALM:ecommerce}
  resource: ${USER_SERVICE_KEYCLOAK_CLIENT_ID:user-service}
  public-client: false
  credentials:
    secret: ${USER_SERVICE_KEYCLOAK_SECRET}

keycloak-admin:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:ecommerce}
  resource: ${USER_SERVICE_ADMIN_KEYCLOAK_CLIENT_ID:user-service-admin}
  public-client: false
  credentials:
    secret: ${USER_SERVICE_ADMIN_KEYCLOAK_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true