version: "3.8"

services:

#  kafka:
#    image: wurstmeister/kafka:latest
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://${KAFKA_BOOTSTRAP_SERVERS}
#      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#      KAFKA_LISTENER_NAME_INSIDE: INSIDE
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
#      KAFKA_LISTENER_PORT: 9093
#      KAFKA_LISTENER_NAME: INSIDE
#      KAFKA_LISTENER_INTERNAL_PORT: 9093
#      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
#    ports:
#      - "9093:9093"
#    networks:
#      - ecommerce_network
#    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/
    ports:
      - "8080:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak-export/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - ecommerce_network
    restart: always

  service-registry:
    image: adelinv2/react-spring-ecommerce.service-registry
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      SERVICE_REGISTRY_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - ecommerce_network
    restart: always
#    depends_on:
#      - kafka

  api-gateway:
    image: adelinv2/react-spring-ecommerce.api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER: service-registry:8761
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      API_GATEWAY_PORT: 8000
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
    ports:
      - "8000:8000"
    depends_on:
      - service-registry
      - keycloak
#      - kafka
    networks:
      - ecommerce_network
    restart: always

  product-service:
    image: adelinv2/react-spring-ecommerce.product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PRODUCT_DB_URL: ${PRODUCT_DB_URL}
      PRODUCT_DB_USERNAME: ${PRODUCT_DB_USERNAME}
      PRODUCT_DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
      PRODUCT_SERVICE_PORT: 8081
    depends_on:
      - service-registry
      - keycloak
#      - kafka
    networks:
      - ecommerce_network
    restart: always

  user-service:
    image: adelinv2/react-spring-ecommerce.user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_DB_URL: ${USER_DB_URL}
      USER_DB_USERNAME: ${USER_DB_USERNAME}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
      USER_SERVICE_PORT: 8082
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      USER_SERVICE_KEYCLOAK_SECRET: ${USER_SERVICE_KEYCLOAK_SECRET}
      USER_SERVICE_ADMIN_KEYCLOAK_SECRET: ${USER_SERVICE_ADMIN_KEYCLOAK_SECRET}
      USER_SERVICE_KEYCLOAK_CLIENT_ID: ${USER_SERVICE_KEYCLOAK_CLIENT_ID}
    depends_on:
#      - kafka
      - service-registry
      - keycloak
    networks:
      - ecommerce_network
    restart: always

  image-service:
    image: adelinv2/react-spring-ecommerce.image-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
      IMAGE_SERVICE_PORT: 8083
    depends_on:
       - service-registry
       - keycloak
#      - kafka
    networks:
      - ecommerce_network
    restart: always

  review-service:
    image: adelinv2/react-spring-ecommerce.review-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REVIEW_DB_URL: ${REVIEW_DB_URL}
      REVIEW_DB_USERNAME: ${REVIEW_DB_USERNAME}
      REVIEW_DB_PASSWORD: ${REVIEW_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      EUREKA_SERVER_URL: http://service-registry:8761/eureka/
      REVIEW_SERVICE_PORT: 8084
    depends_on:
      - service-registry
      - keycloak
#      - kafka
    networks:
      - ecommerce_network
    restart: always

networks:
  ecommerce_network:
    driver: bridge