const categories = [
  {
    category: "Laptops, Tablets & Phones",
    subcategories: [
      "Laptops",
      "Windows Laptops",
      "Gaming Laptops",
      "Apple Laptops",
      "Laptop Brands: Asus, Lenovo, HP, Apple, Acer",
      "Laptop Accessories: Bags, Cooling Stands, Notebook HDDs",
      "Mobile Phones",
      "Phone Brands: Samsung, Apple, Motorola, Google, Xiaomi",
      "Phone Accessories: Cases, Screen Protectors, Chargers",
      "Prepaid Card Recharge",
      "Tablets",
      "Tablet Accessories: Cases, Car Mounts, Docking Stations",
      "Wearables & Gadgets: Smartwatches, Fitness Bands, Wireless Earbuds",
      "Product Finder: Laptop",
      "Product Finder: Phones",
      "Refurbished Laptops: Asus, Lenovo, HP, Dell, Acer",
      "Refurbished Phones: Apple, Samsung, Huawei",
      "Refurbished Smartwatches: Apple, Samsung, Huawei",
    ],
  },
  {
    category: "PC, Peripherals & Software",
    subcategories: [
      "Desktops",
      "Monitors",
      "Keyboards & Mice",
      "Printers & Scanners",
      "PC Components",
      "Software & Licenses",
      "Routers & Networking",
    ],
  },
  {
    category: "TV, Audio & Photo",
    subcategories: [
      "Televisions",
      "Home Audio Systems",
      "Headphones",
      "Streaming Devices",
      "Cameras",
      "Drones",
      "Camera Accessories",
    ],
  },
  {
    category: "Appliances & Climate Control",
    subcategories: [
      "Washing Machines",
      "Refrigerators",
      "Microwaves & Ovens",
      "Dishwashers",
      "Vacuum Cleaners",
      "Air Conditioners",
      "Fans & Air Purifiers",
    ],
  },
  {
    category: "Gaming, Books & Office",
    subcategories: [
      "Game Consoles",
      "Video Games",
      "Board Games",
      "Gaming Chairs",
      "Office Furniture",
      "Stationery",
      "Books",
    ],
  },
  {
    category: "Grocery",
    subcategories: [
      "Snacks",
      "Drinks",
      "Coffee & Tea",
      "Canned Goods",
      "Cleaning Supplies",
      "Organic Products",
    ],
  },
  {
    category: "Fashion",
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Shoes",
      "Watches",
      "Accessories",
    ],
  },
  {
    category: "Personal Care & Cosmetics",
    subcategories: [
      "Skin Care",
      "Hair Care",
      "Oral Care",
      "Shavers & Trimmers",
      "Makeup",
      "Fragrances",
    ],
  },
  {
    category: "Home, Garden & DIY",
    subcategories: [
      "Furniture",
      "Home Decor",
      "Lighting",
      "Garden Tools",
      "DIY Tools",
      "Storage Solutions",
    ],
  },
  {
    category: "Sport & Travel",
    subcategories: [
      "Fitness Equipment",
      "Outdoor Gear",
      "Bikes & Scooters",
      "Camping Equipment",
      "Luggage",
      "Travel Accessories",
    ],
  },
  {
    category: "Auto, Moto & Insurance",
    subcategories: [
      "Car Accessories",
      "Motor Oil & Fluids",
      "Tires & Wheels",
      "Batteries",
      "Car Electronics",
      "Insurance Services",
    ],
  },
  {
    category: "Toys, Kids & Baby",
    subcategories: [
      "Toys",
      "Educational Toys",
      "Baby Strollers",
      "Car Seats",
      "Nursery Furniture",
      "Kids' Fashion",
    ],
  },
];

export default categories;
