server:
  port: ${PRODUCT_SERVICE_PORT:80}

spring:
  application:
    name: product-service

  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      retries: 3
      acks: all
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"${KAFKA_PASSWORD}\";"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8080/realms/ecommerce}

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080/auth}
  realm: ${KEYCLOAK_REALM:ecommerce}
  resource: ${KEYCLOAK_CLIENT_ID:product-service}
  public-client: false
  credentials:
    secret: ${PRODUCT_SERVICE_KEYCLOAK_SECRET}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
