server:
  port: ${PRODUCT_SERVICE_PORT:80}

spring:
  application:
    name: product-service

  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      retries: 3
      acks: all
    consumer:
      group-id: product-service
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: https://veldara-service-registry.azuremicroservices.io/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
