server:
  port: ${API_GATEWAY_PORT:80}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://veldara-product-service.azurewebsites.net
          predicates:
            - Path=/api/product/**

        - id: discovery-server
          uri: http://veldara-service-registry.azurewebsites.net
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/

eureka:
  client:
    service-url:
      defaultZone: http://veldara-service-registry.azurewebsites.net/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
