server:
  port: ${API_GATEWAY_PORT:80}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/api/image/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/review/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8080/realms/ecommerce}

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080/auth}
  realm: ${KEYCLOAK_REALM:ecommerce}
  resource: ${KEYCLOAK_CLIENT_ID:product-service}
  public-client: false
  credentials:
    secret: ${PRODUCT_SERVICE_KEYCLOAK_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
