name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build for api-gateway
      - name: Build api-gateway
        run: |
          cd backend/api-gateway
          mvn clean install -DskipTests

      # Build for service-registry
      - name: Build service-registry
        run: |
          cd backend/service-registry
          mvn clean install -DskipTests

      # Build for product-service
      - name: Build product-service
        run: |
          cd backend/product-service
          mvn clean install -DskipTests

      - name: Upload artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-apps
          path: |
            backend/api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar
            backend/service-registry/target/service-registry-0.0.1-SNAPSHOT.jar
            backend/product-service/target/product-service-0.0.1-SNAPSHOT.jar

      - name: Deploy API Gateway
        run: |
          az spring app deploy --name api-gateway \
            --service ${{ secrets.AZURE_SPRING_APPS_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --artifact-path backend/api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar

      - name: Deploy Product Service
        run: |
          az spring app deploy --name product-service \
            --service ${{ secrets.AZURE_SPRING_APPS_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --artifact-path backend/product-service/target/product-service-0.0.1-SNAPSHOT.jar

      - name: Deploy Service Discovery
        run: |
          az spring app deploy --name service-discovery \
            --service ${{ secrets.AZURE_SPRING_APPS_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --artifact-path backend/service-registry/target/service-registry-0.0.1-SNAPSHOT.jar
