name: Build and Deploy Microservices to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Build for api-gateway
      - name: Build api-gateway
        run: |
          cd backend/api-gateway
          mvn clean install

      # Build for product-service
      - name: Build product-service
        run: |
          cd backend/product-service
          mvn clean install

      # Build for service-registry
      - name: Build service-registry
        run: |
          cd backend/service-registry
          mvn clean install

      - name: Upload artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-apps
          path: |
            backend/api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar
            backend/product-service/target/product-service-0.0.1-SNAPSHOT.jar
            backend/service-registry/target/service-registry-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: java-apps

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy api-gateway
      - name: Deploy api-gateway to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-gateway'
          package: './backend/api-gateway/target/api-gateway.jar'

      # Deploy product-service
      - name: Deploy product-service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-service'
          package: './backend/product-service/target/product-service.jar'

      # Deploy service-registry
      - name: Deploy service-registry to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'service-registry'
          package: './backend/service-registry/target/service-registry.jar'
